-- MySQL Script generated by MySQL Workbench
-- Mon Apr 17 08:49:46 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema auth_service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema auth_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `auth_service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `auth_service` ;

-- -----------------------------------------------------
-- Table `auth_service`.`privilege`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_service`.`privilege` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auth_service`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_service`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auth_service`.`roles_privileges`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_service`.`roles_privileges` (
  `role_id` INT NOT NULL,
  `privilege_id` INT NOT NULL,
  INDEX `FK_role_id_idx` (`role_id` ASC) VISIBLE,
  INDEX `FK_privilege_id_idx` (`privilege_id` ASC) VISIBLE,
  CONSTRAINT `FK_privilege_id`
    FOREIGN KEY (`privilege_id`)
    REFERENCES `auth_service`.`privilege` (`id`),
  CONSTRAINT `FK_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_service`.`role` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auth_service`.`user_account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_service`.`user_account` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `auth_service`.`users_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `auth_service`.`users_roles` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `FK_role_id_idx` (`role_id` ASC) VISIBLE,
  INDEX `FK_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `FK_user_roles_role_id_idx` (`role_id` ASC) VISIBLE,
  INDEX `FK_user_roles_user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK_user_roles_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `auth_service`.`role` (`id`),
  CONSTRAINT `FK_user_roles_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `auth_service`.`user_account` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
